[Feat/YS-31] 구글 OAuth 로그인 구현
YAPP-Github/25th-Web-Team-2-BE pull request #13
Opened 2024-12-30 20:12 UTC by chock-cho

## 💡 작업 내용
- 구글 OAuth 로그인 구현

## ✅ 셀프 체크리스트
- [ ] PR 제목을 형식에 맞게 작성했나요?
- [ ] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요?
- [ ] 테스트는 잘 통과했나요?
- [ ] 빌드에 성공했나요?
- [ ] 본인을 assign 해주세요.
- [ ] 해당 PR에 맞는 label을 붙여주세요.

## 🙋🏻‍ 확인해주세요
- 관련된 Discussion 등이 있다면 첨부해주세요

2025-01-02 12:47 UTC, Ji-soo708 requested changes
전체적으로 잘 구현하셨고 테스트도 정말 꼼꼼하게 해주셨습니다! 👏 다만 몇 가지 개선할 부분이나 논의하고 싶은 부분을 제안드리고 싶어 Request Changes합니다.


**1. 서비스 계층 추상화에 대해**
클린 아키텍처의 핵심 원칙 중 하나인 DIP을 지키기 위해서는 Service/Repository 계층을 추상화하는 것이 더 바람직하다고 생각합니다. Service 인터페이스를 정의하고, 실제 구현체는 infrastructure 계층에서 구현해 application 계층이 infrastructure 계층에 의존하지 않도록 하는 것이 더 적합하다고 생각하는데 어떻게 생각하시나요?
물론, 이 방식은 코드의 유연성과 유지보수성을 향상시킬 수 있지만, 파일이 많아지고 구조가 복잡해지는 단점이 있을 수 있습니다. 그래서 이 부분은 지금 수정님과 협의하여 균형을 찾아가면 좋겠습니다. ☺️

**2. OAuth 로그인 후 토큰 발급 방식**
코드를 봤을 때 제가 이해하기로는 사용자가 OAuth 로그인을 하면, OAuth 토큰을 발급받는 것으로 이해했습니다. 혹시 맞을까요?
맞다면 제 생각에는 OAuth 로그인 시, OAuth 토큰을 그대로 주는 것보다는 정상적인 사용자가 로그인하면 바로 accessToken과 refreshToken을 발급하는 방식이 더 직관적이고 효율적일 것 같습니다.
이렇게 하면 사용자는 한 번의 요청으로 필요한 모든 정보를 받을 수 있고, 프론트엔드에서도 보다 간편하게 처리할 수 있습니다. 별도의 추가 API 호출 없이 로그인 후 즉시 토큰을 발급해주는 것이 흐름을 간소화할 수 있다고 생각하는데 수정님은 어떻게 생각하는지 궁금합니다!

**3. 클린 아키텍처에서의 Service 역할**
개인적으로 UseCase와 Service의 역할을 명확히 구분하기가 어렵더라고요. 수정님은 이번 PR에서 Service를 구현하셨는데, 어떻게 UseCase와 Service의 목적과 역할을 구분하셨는지 의견을 듣고 싶습니다!


전체적으로 잘 구현하셔서 작은 조정들만 고려하면 좋을 거 같습니다! 고생하셨습니다. 👏

2025-01-02 12:47 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/controller/OauthController.kt
> +    private val oauthService: OauthService
`/v1/auth`에서는 OAuth 로그인뿐만 아니라 리프레시 토큰을 이용한 액세스 토큰 갱신 API도 추가되어야 해서, AuthController가 더 적합할 것 같습니다!

2025-01-02 12:47 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/dto/response/OauthTokenResponse.kt
> +)
혹시 OAuth 로그인한 사용자에게 응답으로 바로 `TokenProvider`를 이용해 accessToken과 refreshToken을 발급하는 방식은 어떨까요?

사용자가 로그인을 한 후, 즉시 accessToken과 refreshToken을 발급받으면 별도로 추가 API를 호출할 필요가 없어서 흐름이 간단하고 직관적일 것 같아요. 한 번의 요청으로 필요한 정보가 모두 제공되므로, 프론트엔드에서도 쉽게 처리할 수 있을 거라 생각합니다. #16의 액세스 토큰 재발급 API처럼요! 😊

2025-01-02 12:47 UTC, Ji-soo708 commented on src/main/resources/application.yml
> +    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
해당 PR이 머지되기 전에 꼭 DEV_YML 내용을 갱신해주세요~

2025-01-02 12:47 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
> +}
제가 이해한 바로는, 클린 아키텍처에서 중요한 **DIP**을 지키기 위해서는 서비스 계층을 추상화하는 것이 올바른 접근이라고 생각합니다.
Service 인터페이스를 정의하고, 실제 구현체는 infrastructure 계층에서 구현하도록 하여 application 계층이 infrastructure에 의존하지 않도록 해야 합니다. 다만, 이렇게 구현하면 파일이 많아지는 단점이 있습니다.

따라서, 다음 두 가지 방식 중에서 어떤 것이 더 적합할지 고민해볼 필요가 있을 거 같습니다.
1. 클린 아키텍처 원칙에 따라 추상화를 철저히 한다.
2. 융통성 있게 상황에 맞게 조정한다.

수정님은 어떤 방향이 더 낫다고 생각하나요?

2025-01-02 12:47 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/dto/response/OauthTokenResponse.kt
> +)
```
public class OAuthTokenResponse {

    private String accessToken; // jwt access-token
    private String refreshToken; // jwt refresh-token
    private String email;
    private Boolean isRegistered; // 회원가입 여부
}
```

이전 프로젝트에서는 OAuth 로그인을 호출하면 이렇게 응답을 제공했습니다!

2025-01-02 13:12 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/presentation/api/config/handler/OauthSuccessHandler.kt
> +//        SecurityContextHolder.getContext().authentication = newAuthentication
넵 맞습니다 !

2025-01-02 14:09 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/application/service/MemberService.kt
> +}
1/2 서버 회의에서는 추상화를 철저히 하지만, 이번 주 주말 해커톤까지는 MVP를 빠르게 개발하는 것이 우선이므로, 추후 리팩터링을 통해 개선하기로 결정했습니다.

2025-01-02 22:03 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/infrastructure/database/repository/MemberRepository.kt
> +@Repository
명시성을 위해서였는데, `@Repository` 를 추가하는 것이 중복된 선언이라는 지수님 의견이 일부 동의해서 반영하겠습니다☺️

2025-01-03 00:50 UTC, Ji-soo708 reviewed
제안해드린 로직대로 수정하면서 많은 변경사항이 있었을 텐데, 정말 잘 구현하신 것 같아요! 👏 개인적으로 FeignClient가 HTTP 클라이언트 호출을 추상화해줘서 DIP 원칙을 따르기 좋다고 생각해요. 저희 프로젝트가 클린 아키텍처라면 FeignClient와 잘 어울릴 거라고 봅니다!

추가로 코멘트를 남길 부분이 있어서 확인 부탁드려요~

2025-01-03 00:50 UTC, Ji-soo708 commented on build.gradle.kts
> +	implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
같은 dependency가 두 번 추가된 것 같습니다! 그리고 이제 FeignClient 라이브러리를 사용해서 구현할 예정인데, 이 라이브러리도 필요할지 궁금합니다.

2025-01-03 00:50 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/application/service/OauthService.kt
> +}
엔터 라인 한 번 쳐주세요~

2025-01-03 00:50 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoUseCase.kt
> +            val name = userInfo.name as? String?: throw OAuth2NameNotFoundException()
현재 로직에서 `name`이 필요하지 않으며, 미래에도 활용될 가능성이 낮다고 판단되면 해당 코드를 제거해도 좋을 거 같아요!

2025-01-03 00:50 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/domain/exception/LoginRoleMismatchException.kt
> +class LoginRoleMismatchException(
저는 https://github.com/YAPP-Github/25th-Web-Team-2-BE/pull/16 에서 `Login` 대신 `SignIn`을 사용했습니다! 이름 통일성을 위해 회원가입을 `SignUp`으로 지칭한다면, 로그인도 `SignIn`으로 네이밍하는 것이 더 좋다고 판단했습니다. 혹시 수정님도 회원가입을 `SignUp`으로 한다면, 로그인도 `SignIn`으로 통일하는 게 어떨까요?

2025-01-03 00:50 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
> +            it.anyRequest().authenticated()
혹시 이 부분이 `/v1/auth/oauth/**`에 해당하는 요청에 대해서만 인증 없이 접근을 허용한다는 코드일까요?

그렇다면 [추후 추가될 기능](https://github.com/YAPP-Github/25th-Web-Team-2-BE/pull/16) 을 위해서 `/v1/auth/**` 로 하면 더 좋을 거 같습니다! 👍

2025-01-03 00:50 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/config/WebSecurityConfig.kt
>          .build()
Swagger 추가하면서 이 부분 고려하는 걸 놓쳤는데 추가해주셔서 감사합니다 ☺️

2025-01-03 00:50 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
> +}
해당 클래스 내용이 비어있는 것으로 보입니다. 혹시 `OAuthController`의 이름을 `AuthController`로 변경하려다가 관련된 코드 업데이트를 놓치신 걸까요?

2025-01-03 00:50 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/controller/OauthController.kt
> +    @Operation(summary = "Google OAuth 로그인 API", description = "Google OAuth 로그인 후 인증 정보를 반환합니다")
지금 URI가 세부적으로 나누어져 있어 좋은 점이 있지만, 제가 생각할 때 `auth`와 `oauth`가 중복된다는 느낌이 있습니다.

저희 서비스에서는 OAuth 로그인만 제공하므로 URI에서 `oauth`를 제외하고 `/v1/auth/google` 또는 `/v1/auth/google/login`처럼 표현해도 충분히 API의 역할을 잘 전달할 수 있을 거라 생각하는데, 혹시 어떠신가요??

2025-01-03 03:09 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/application/service/OauthService.kt
> +}
반영하겠습니다! 
앞으로 작업 전에 EOF 문제 있는지까지 꼼꼼히 처리해야겠네요!

2025-01-03 03:09 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/application/usecase/FetchGoogleUserInfoUseCase.kt
> +            val name = userInfo.name as? String?: throw OAuth2NameNotFoundException()
반영하겠습니다~

2025-01-03 03:11 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/domain/exception/LoginRoleMismatchException.kt
> +class LoginRoleMismatchException(
저는 항상 로그인 로직을 `Login` 으로 네이밍해왔었는데요, 회원가입이 `SignUp` 이라면 `SignIn` 으로 네이밍하는 편이 좋다는 지수님 의견에 저도 동의합니다!
반영하겠습니다.

2025-01-03 03:13 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/presentation/api/controller/AuthController.kt
> +}
네 정확합니다 😅 사실 이번 브랜치 이후에 작업들을 하면서 작업 내용이 일부 혼재가 되어있어 (이후에 참여자 회원가입 로직 등등...) 작업 내용을 `stash` 하고 커밋 내용이 반영되는 파일들을 걸러내는 과정 중에 놓친 것 같습니다!
좋은 지적 감사합니다~🖐️

2025-01-03 03:13 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/presentation/api/controller/OauthController.kt
> +    @Operation(summary = "Google OAuth 로그인 API", description = "Google OAuth 로그인 후 인증 정보를 반환합니다")
해당 내용 반영했습니다!

2025-01-03 04:55 UTC, Ji-soo708 approved these changes
수고하셨습니다! 전반적으로 잘 구현되었다고 생각해 approve하고 merge합니다! 👏

2025-01-03 04:55 UTC, merged