feat: 패키지 구조 및 예외처리 관련 로직 설정
YAPP-Github/25th-Web-Team-2-BE pull request #3
Opened 2024-12-23 00:32 UTC by chock-cho

## 👋 개요
- 클린 아키텍처 적용한 패키지 구조 및 예외처리 관련 로직 설정

## 💻 작업사항
- 클린 아키텍처 패턴 적용하여, 패키지 구조 초기 설정
- 예외처리 로직 작성
- SOLID 원칙 준수하도록 설계
-  [해당 링크](https://www.notion.so/oneg1107/842c1db31ad24a558885665aafb27976)에서  패키지 구조 관련 자세한 설계도 참고 가능 

## ⚠️ 주의사항
- PR 제목의 형식은 커밋 메시지의 제목 형식과 동일하다.
- 제목에는 이 PR이 무엇을 했는지 명시해주기
- ex) feat: 로그인 토큰 발행 기능 추가

2024-12-24 01:06 UTC, Ji-soo708 requested changes
수고하셨습니다!
패키지 구조는 지금 좋은 거 같아요! 같이 클린아키텍처 공부해가면서 바꾸면 좋은 부분 있으면 천천히 바꿔도 좋을 거 같아요 👍
코드 쭉 살펴보면서 고쳐야 하는 부분과 궁금한 점들 남겼습니다~

2024-12-24 01:06 UTC, Ji-soo708 commented on src/main/kotlin/com/dobby/backend/presentation/api/dto/apiPayload/ApiResponse.kt
> +package com.dobby.backend.presentation.api.dto.apiPayload
`apiPayload` 패키지명 대신 `payload`는 어떠신가요? 이미 `api`라는 상위 패키지가 존재해서 `payload`라는 이름도 충분히 이해되고 직관적일 거 같아요!

2024-12-25 06:24 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/domain/object/MemberObject.kt
> +package com.dobby.backend.domain.`object`
네 도메인 클래스 용도입니다.
직관적으로 네이밍하려는 과정에서 생긴 것 같네요! 😅
말씀대로 패키지 명 model로 다시 수정하겠습니다

2024-12-25 06:25 UTC, chock-cho commented on src/main/kotlin/com/dobby/backend/presentation/api/config/handler/TempHandler.kt
> +class TempHandler(errorCode: BaseErrorCode) : GeneralExcpetion(errorCode)
네 커스텀예외를 다루는 클래스가 맞습니다! 수정하도록 하겠습니다 ☺️

2024-12-26 11:56 UTC, Ji-soo708 approved these changes
LGTM! 수고하셨습니다~ 👍

2024-12-26 12:02 UTC, merged